name: Trigger Dispatch

on:
  push:
    branches:
      - main

# REPO_WEBSITE_ACCESS_TOKEN is a PAT token that allows andy108369/repo-aep to trigger workflows in andy108369/repo-website via repository dispatch.
# PAT token repo access is limited to andy108369/repo-website only with the following permissions necessary for triggering the workflow:
# - Actions: Read & Write (Trigger workflows)
# - Workflows: Read & Write (Dispatch events)
# - Contents: Read & Write (Required for repository dispatch)
# - Metadata: Read (Mandatory)

jobs:
  dispatch-event:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event to repo-website
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.REPO_WEBSITE_ACCESS_TOKEN }}" \
                  -H "Content-Type: application/json" \
                  https://api.github.com/repos/andy108369/repo-website/dispatches \
                  -d '{"event_type": "test-trigger"}')

          [[ "$STATUS" -ge 200 && "$STATUS" -lt 300 ]] || { echo "Error: HTTP $STATUS"; exit 1; }
